version: 2

models:
  - name: stg_gios__stations
    description: "Cleaned & typed GIOS stations"
    columns:
      - name: station_id
        tests: [not_null, unique]
      - name: station_name
        tests: [not_null]
      - name: latitude
        tests:
          - dbt_utils.accepted_range:
              min_value: 49.0
              max_value: 55.0
      - name: longitude
        tests:
          - dbt_utils.accepted_range:
              min_value: 14.0
              max_value: 24.5

  - name: stg_gios__measurements
    description: "Cleaned hourly measurements"
    columns:
      - name: sensor_id
        tests: [not_null]
      - name: measured_at
        tests: [not_null]
      - name: pollutant_code
        tests:
          - accepted_values:
              values: ['PM10', 'PM2.5', 'NO2', 'SO2', 'O3', 'CO', 'C6H6']
      - name: value
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
